# Generated by Django 3.1 on 2020-09-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_movies_average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
