# Generated by Django 3.1 on 2020-09-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_watched_movies_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watched_movies_average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
