# Generated by Django 3.1 on 2020-09-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200926_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_movies_genres',
            field=models.TextField(blank=True, default=''),
        ),
    ]
