# Generated by Django 3.1 on 2020-09-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200927_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watched_movies_genres',
        ),
    ]
