# Generated by Django 3.1 on 2020-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_profile_watched_movies_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_movies_genres',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
