# Generated by Django 3.1 on 2020-09-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_watched_movies_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='watched_movies_genres',
        ),
    ]
