# Generated by Django 3.1 on 2020-08-23 06:51

import django.core.validators
from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), movies.models.max_value_current_year])),
                ('plot', models.CharField(max_length=2000)),
                ('poster_url', models.URLField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
