# Generated by Django 3.1 on 2020-09-12 16:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.SlugField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), movies.models.max_value_current_year])),
                ('plot', models.CharField(max_length=2000)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('full_json_details', models.JSONField(default=None)),
            ],
            options={
                'permissions': [('paid_for_membership', 'Has access to premium content')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=300, null=True)),
                ('review_text', models.CharField(max_length=10000, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('author_rating', models.IntegerField(blank=True, null=True)),
                ('contains_spoilers', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
            ],
        ),
    ]
