# Generated by Django 3.1 on 2020-09-12 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
