# Generated by Django 3.1 on 2020-08-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_full_json_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.SlugField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
