# Generated by Django 3.1 on 2020-08-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200824_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
