# Generated by Django 3.1 on 2020-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200824_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.SlugField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
