# Generated by Django 3.1 on 2020-09-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200914_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watched_by',
        ),
    ]
