# Generated by Django 3.1 on 2020-08-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
