# Generated by Django 3.1 on 2020-08-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20200825_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': [('paid_for_membership', 'Has access to premium content')]},
        ),
    ]
