# Generated by Django 3.1 on 2020-08-29 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_auto_20200825_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.ManyToManyField(related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
