# Generated by Django 3.1 on 2020-08-29 16:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0009_movie_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
