# Generated by Django 3.1 on 2020-09-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20200829_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='author_rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='review',
            name='contains_spoilers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='review_text',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='review',
            name='submission_date',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
