# Generated by Django 3.1 on 2020-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20200910_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
